### ISSUE TITLE
Invalid file extension

### ISSUE THREAD

**Issue by palash25** [swetajena98/guess_the_word-cpp-game#1]
Hi there :wave: Just stumbled upon your profile after your follow (thank you for that :pray: )

Why have you saved your cpp code in a text file instead of `.cpp`?

Please change the extension and run it. Once you have done that ping me on slack and we will help you enhance this project 

And don't be shy of sharing your projects. Just put the link on slack and ask for others opinion and we will help you make it better.

And also kudos for trying to start a project.

**Comment by swetajena98** [comment]
Thank you @palash25 .
I changed the file extension and it runs fine.
